[package]
name = "degaart-blog"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
chrono = "0.4.19"
handlebars = "4.3.3"
once_cell = "1.13.0"
pulldown-cmark = "0.9.2"
regex = "1.6.0"
serde = { version = "1.0.140", features = ["derive"] }



